REM File: .bas
REM Data: 
REM Programmer: Yuriy Lomako
REM Description: 
REM -------------------------------------------------------------------

SCREEN 7
LINE (95, 60)-(95, 20), 1
LINE (95, 60)-(95, 100), 2
LINE (95, 60)-(50, 60), 3
LINE (95, 60)-(135, 60), 4
LINE (95, 60)-(55, 20), 5
LINE (95, 60)-(135, 20), 6
LINE (95, 60)-(135, 100), 7
LINE (95, 60)-(55, 100), 8
                                    

