REM File: .bas
REM Data: 
REM Programmer: Yuriy Lomako
REM Description: 
REM -------------------------------------------------------------------

CLS
20 INPUT "COME TI CHIAMI? "; A$
   GOSUB 500
30 INPUT "COME STAI? "; B$
   GOSUB 500
40 INPUT "QUANTI ANNI COMPI? "; C$
   GOSUB 500
50 INPUT "QUAL'E LA TUA REGIONE? "; D$
   GOSUB 500
60 INPUT "COSA TI PIACE DA BERE? "; E$
   GOSUB 500
70 INPUT "MA SCUSA STAI BENE O NO!? "; F$
GOSUB 500
80 END

500 PRINT "/`/`/`/`/`/`/`/`/`/`/`/`/`/`/`/`/`/`/`/`/`/`/`/`/`/`/`/`/`"
510 PRINT "----------------------------------------------------------"
520 PRINT "**********************************************************"
530 PRINT "=========================================================="
555 RETURN
 

