REM File: .bas
REM Data: 
REM Programmer: Yuriy Lomako
REM Description: 
REM -------------------------------------------------------------------

CLS
PRINT " scolco dnei arturo budet na pliagie "
INPUT p
h = 24
s = h * p
PRINT " arturo budet naxoditsa "; s; " ciasov "
PRINT
PRINT
PRINT
PRINT
PRINT " scolco ciasov otdihaiet doma arturo cogdii den? "
INPUT x
PRINT x
z = 24 - x
q = z * p
PRINT " arturo budet na pliagie "; q; " ciasov v tiecienie svoih canicul "

