REM File: .bas
REM Data: 
REM Programmer: Yuriy Lomako
REM Description: 
REM -------------------------------------------------------------------

5   CLS
10  PRINT "ˆŒŸ "
15  PRINT ".-.-.-.-.-.-.-.-.-.-."
20  INPUT A$
30  PRINT "Ž’—…‘’‚Ž "
35  PRINT ".-.-.-.-.-.-.-.-.-.-."
40  INPUT B$
50  PRINT "”€Œˆ‹ˆŸ "
55  PRINT ".-.-.-.-.-.-.-.-.-.-."
60  INPUT C$
70  PRINT "„€’€ Ž†„…ˆŸ "
75  PRINT ".-.-.-.-.-.-.-.-.-.-."
80  INPUT D$
90  PRINT
100 PRINT
110 PRINT
120 PRINT A$ + " " + B$ + " " + C$
130 PRINT "Ž„ˆ‹‘Ÿ "; D$







