REM File: .bas
REM Data: 
REM Programmer: Yuriy Lomako
REM Description: 
REM -------------------------------------------------------------------

CLS
10  PRINT "        x"
20  PRINT "        xx"
30  PRINT "        xxx"
40  PRINT "        xxxx"
50  PRINT "        xxxxx"
60  PRINT "        xxxxxx"
70  PRINT "        xxxxxxx"
80  PRINT "        xxxxxxxx"
90  PRINT "        xxxxxxxxx"
100 PRINT "        xxxxxxxxxx"
110 PRINT "        xxxxxxxxxxx"
120 PRINT "        xxxxxxxxxxxx"
130 PRINT "        x"
140 PRINT "        x"
150 PRINT " xxxxxxxxxxxxxxxxxxxxxxx"
160 PRINT "  xxxxxxxxxxxxxxxxxxxxx"
170 PRINT "   xxxxxxxxxxxxxxxxxxx"
180 PRINT "    xxxxxxxxxxxxxxxxx"
190 END

